using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Mayhem.Core
{
    public static class RandomNameGenerator
    {
        private static string[] m_RandomNameList = new string[]
        {
            "Dario",
            "Guy",
            "Gene",
            "Claudio",
            "Stan",
            "Fausto",
            "Riley",
            "Darwin",
            "Long",
            "Samual",
            "Tyron",
            "Kieth",
            "Truman",
            "Denny",
            "David",
            "Tad",
            "Jacob",
            "Freeman",
            "Rogelio",
            "Dino",
            "Benjamin",
            "Isaias",
            "Allen",
            "Vicente",
            "Quincy",
            "Huey",
            "Ervin",
            "Renato",
            "Carmelo",
            "Aaron",
            "Ellsworth",
            "Terrell",
            "Harvey",
            "Josef",
            "Lucien",
            "Eric",
            "Roman",
            "Damien",
            "Curtis",
            "Sydney",
            "Nigel",
            "Harlan",
            "Desmond",
            "Stacy",
            "Mac",
            "Brant",
            "Claud",
            "Harland",
            "Granville",
            "Dewayne",
            "Thresa",
            "Nickole",
            "Randi",
            "Valorie",
            "Anjelica",
            "Leonida",
            "Valrie",
            "Christie",
            "Megan",
            "Catalina",
            "Queen",
            "Roxana",
            "Addie",
            "Amanda",
            "Kary",
            "Kira",
            "Velva",
            "Danna",
            "Janyce",
            "Edyth",
            "Synthia",
            "Kimiko",
            "Annemarie",
            "Renae",
            "Isidra",
            "Maragaret",
            "Flo",
            "Alvina",
            "Denita",
            "Margarite",
            "Stasia",
            "Donella",
            "Sherill",
            "Herta",
            "Bernetta",
            "Emilie",
            "Reynalda",
            "Adeline",
            "Enola",
            "Celeste",
            "Corrin",
            "Vesta",
            "Adele",
            "Tricia",
            "Lashell",
            "Katlyn",
            "Bertie",
            "Imelda",
            "Leeann",
            "Carole"
        };


        public static string GetName()
        {
            return m_RandomNameList[new Random((int)(DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond)).Next(0, m_RandomNameList.Length)];

        }
    }
}
